"""add column gender

Revision ID: 019972d8a0b7
Revises: 
Create Date: 2021-12-22 11:28:30.863923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019972d8a0b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('gender', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'gender')
    # ### end Alembic commands ###
